system_prompt: You are a consumer in a market research study. Your task is to provide
  answers to the questions given. Please respond with ONLY the digit of the response.
  Do not provide any other text, explanation, or punctuation.
rounds:
- key: '3'
  segments:
  - segment_label: Fixed Segment
    segment_text: "**Instructions:**\n\nPlease indicate your agreement with the statement\
      \ below with a number between 1 and 7. \n1: Strongly disagree\n7: Strongly agree"
    segment_id: 5b8fdsdfd
  - segment_label: Treatment Segment
    segment_text: '**Statement**


      {size}


      {nationality} people should always buy {nationality}-made {product}s instead
      of imports.'
    segment_id: 29fsdfsde8d
  round_type: scales
  factors_list:
  - - nationality
    - - nationality|name: america
        nationality|text: American
      - nationality|name: china
        nationality|text: Chinese
  - - product
    - - product|name: tv
        product|text: TV
      - product|name: tablet
        product|text: Tablet
  factor_products:
  - - nationality|name: american
      nationality|text: American
  - - nationality|name: chinese
      nationality|text: Chinese
- key: 549b110f-588d-46af-aa4f-f28b1573a5fa
  segments:
  - segment_label: Treatment Segment
    segment_text: '**Statement**


      Only those products that are unavailable in {country} should be imported. '
    segment_id: '78737'
  factors_list:
  - - country
    - - country|name: america
        country|text: the U.S.
      - country|name: china
        country|text: China
  round_type: scales
block_variables:
- - size
  - - size|name: small
      size|text: Small
    - size|name: large
      size|text: Large
k: 10
test: true
sleep_amount: 0.05
models_to_test:
- google-gemini-2.5-flash-lite
- deepinfra-deepseek-ai/DeepSeek-V3.1-Terminus
- openai-gpt-4.1-nano
- anthropic-claude-3-5-haiku-20241022
randomize: true
paper_url: https://doi.org/10.1177/002224378702400304
api_keys:
  openai: null
  anthropic: null
  google: null
  deepinfra: null
  test: null
