system_prompt: You are a consumer in a market research study. Your task is to rank
  the options given. Please respond with ONLY the array of the rankings (most preferred
  to least preferred). Do not provide any other text, explanation, or punctuation.
rounds: []
block_variables: []
k: 1
test: true
sleep_amount: 0.01
models_to_test:
- deepinfra-Qwen/Qwen3-Next-80B-A3B-Instruct
randomize: true
paper_url: https://doi.org/10.1177/002224378702400304
api_keys:
  openai: null
  anthropic: null
  google: null
  deepinfra: null
  alibabacloud: null
  test: null
