system_prompt: You are a consumer in a market research study. Your task is to choose
  between two options. Please respond with ONLY the number of the option you would
  choose (1 or 2). Do not provide any other text, explanation, or punctuation.
factors_list:
- - product
  - - product|name: product_laptop
      product|text: laptop
    - product|name: product_tablet
      product|text: tablet
- - brand
  - - brand|name: brand_apple
      brand|text: apple
    - brand|name: brand_noname
      brand|text: no name brand
segments:
- segment_label: Fixed Segment
  segment_text: "**Scenario:**\n    You are considering a purchase.\n\n**Instructions:**\n\
    Please carefully review the options below. "
  segment_id: 5b8fd
- segment_label: Choice Options
  segment_text: '{product} {brand}'
  segment_id: 5dd42
  segment_text_inserted: laptop apple
- segment_label: Choice Options
  segment_text: '{product} {brand}'
  segment_id: 5eedf
  segment_text_inserted: tablet apple
- segment_label: Fixed Segment
  segment_text: '**Question:**

    Which option do you choose? (Respond with 1 or 2)'
  segment_id: 6a435
k: 1
test: true
sleep_amount: 0.1
models_to_test:
- openai-gpt-4.1-nano
- deepinfra-meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8
randomize: true
paper_url: https://doi.org/10.1177/00920703032576
